"""SSH-key challenge-response auth (item 243) and provenance claims (item 245).

The negative cases are the point: a challenge not minted by this relay, an
expired one, a signature from a different key, and an unadmitted key must all
fail. A positive path without those would only prove the happy half of the
mechanism.
"""

from __future__ import annotations

import base64
import pathlib
import shutil
import subprocess
import time

import pytest

from openburrow.relay.config import RelaySettings
from openburrow.relay.errors import AuthError
from openburrow.relay.security import (
    SSH_SIGNATURE_NAMESPACE,
    new_ssh_challenge,
    provenance_extension,
    ssh_fingerprint,
    verify_ssh_challenge,
    verify_ssh_signature,
)

pytestmark = pytest.mark.unit

SECRET = "test-relay-secret"

# Throwaway keypairs generated by cryptography at import time. The public half
# is derived from the private half rather than pasted alongside it: an OpenSSH
# public-key line is the *encoded* key, and a hand-typed "matching" pair that
# doesn't actually match would make every signature test a silent false
# negative.
#
# Three key types rather than one. Ed25519 alone let a dead RSA/ECDSA branch
# ship, because the code that builds the RSA padding could not run under any
# test in this file.
from cryptography.hazmat.primitives import hashes, serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric import ec, padding, rsa  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

_TEST_SK = Ed25519PrivateKey.generate()
_TEST_RSA_SK = rsa.generate_private_key(public_exponent=65537, key_size=2048)
_TEST_EC_SK = ec.generate_private_key(ec.SECP256R1())

#: ``None`` when the OpenSSH client is absent, which is what the interop classes
#: below skip on. The oracle for a fingerprint or a signature format has to be
#: the tool that defines it, not a second copy of our own arithmetic.
SSH_KEYGEN = shutil.which("ssh-keygen")


def _openssh(private_key: object) -> str:
    return (
        private_key.public_key()  # type: ignore[attr-defined]
        .public_bytes(serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH)
        .decode("ascii")
    )


_TEST_ED25519_PK = _openssh(_TEST_SK)
_TEST_RSA_PK = _openssh(_TEST_RSA_SK)
_TEST_EC_PK = _openssh(_TEST_EC_SK)


def _sign_raw(challenge: str) -> str:
    """Ed25519: a bare signature over the challenge, base64-encoded."""
    return base64.b64encode(_TEST_SK.sign(challenge.encode())).decode("ascii")


def _sign_raw_rsa(challenge: str) -> str:
    """RSA: PKCS#1 v1.5 with SHA-256, which is what a binding produces."""
    return base64.b64encode(
        _TEST_RSA_SK.sign(challenge.encode(), padding.PKCS1v15(), hashes.SHA256())
    ).decode("ascii")


def _sign_raw_ec(challenge: str) -> str:
    """ECDSA: DER, which is what a binding produces."""
    return base64.b64encode(_TEST_EC_SK.sign(challenge.encode(), ec.ECDSA(hashes.SHA256()))).decode(
        "ascii"
    )


def _ssh_keygen(*args: str) -> subprocess.CompletedProcess[str]:
    """Run the OpenSSH client. argv is built from literals at each call site."""
    assert SSH_KEYGEN is not None, "guarded by skipif"
    return subprocess.run(  # noqa: S603 - argv is built here, never a shell string
        [SSH_KEYGEN, *args], check=True, capture_output=True, text=True
    )


def _keygen_pair(directory: pathlib.Path, key_type: str) -> tuple[str, pathlib.Path]:
    """Generate a keypair and return its public line and the path to it."""
    private = directory / f"id_{key_type}"
    _ssh_keygen("-q", "-t", key_type, "-N", "", "-C", "probe@test", "-f", str(private))
    public_path = private.with_name(f"{private.name}.pub")
    return public_path.read_text().strip(), public_path


def _sshsig(
    directory: pathlib.Path, key_type: str, message: str, *, namespace: str
) -> tuple[str, str, str]:
    """Sign ``message`` with ``ssh-keygen -Y sign``, the documented client flow.

    Returns the public key, the message, and the armored signature.
    """
    public, public_path = _keygen_pair(directory, key_type)
    private = public_path.with_name(public_path.name.removesuffix(".pub"))
    body = directory / "challenge"
    body.write_text(message, encoding="utf-8")
    _ssh_keygen("-Y", "sign", "-f", str(private), "-n", namespace, str(body))
    return public, message, body.with_name(f"{body.name}.sig").read_text()


class TestChallengeBinding:
    def test_challenge_round_trip(self) -> None:
        challenge, expires = new_ssh_challenge(secret=SECRET)
        assert challenge.startswith("openburrow-relay auth ")
        assert expires > time.time()
        verify_ssh_challenge(challenge, secret=SECRET)  # must not raise

    def test_tampered_nonce_rejected(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        parts = challenge.split()
        parts[3] = "deadbeef" * 4
        with pytest.raises(AuthError):
            verify_ssh_challenge(" ".join(parts), secret=SECRET)

    def test_expired_challenge_rejected(self) -> None:
        challenge, _expires = new_ssh_challenge(secret=SECRET)
        # Re-mint with the same nonce but an expiry in the past: the MAC is over
        # the expiry too, so this forges rather than replays — and forging is
        # what must fail.
        parts = challenge.split()
        nonce = parts[3]
        import hashlib
        import hmac

        old = time.time() - 10_000
        mac = hmac.new(SECRET.encode(), f"{nonce}|{int(old)}".encode(), hashlib.sha256).hexdigest()[
            :32
        ]
        with pytest.raises(AuthError):
            verify_ssh_challenge(
                f"openburrow-relay auth {nonce} exp={int(old)} mac={mac}", secret=SECRET
            )

    def test_challenge_from_another_service_rejected(self) -> None:
        with pytest.raises(AuthError):
            verify_ssh_challenge("gitlab-ci auth 1234", secret=SECRET)

    def test_unprotected_challenge_rejected_when_binding_expected(self) -> None:
        challenge, _ = new_ssh_challenge()  # no secret: unbound form
        with pytest.raises(AuthError):
            verify_ssh_challenge(challenge, secret=SECRET)


class TestSignature:
    def test_valid_signature_verifies(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert verify_ssh_signature(_TEST_ED25519_PK, challenge, _sign_raw(challenge)) is True

    def test_wrong_key_rejected(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        other = Ed25519PrivateKey.generate()
        other_pk = (
            other.public_key()
            .public_bytes(serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH)
            .decode("ascii")
        )
        assert verify_ssh_signature(other_pk, challenge, _sign_raw(challenge)) is False

    def test_challenge_mutation_rejected(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert (
            verify_ssh_signature(_TEST_ED25519_PK, challenge + "x", _sign_raw(challenge)) is False
        )

    def test_garbage_signature_is_false_not_error(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert verify_ssh_signature(_TEST_ED25519_PK, challenge, "not-base64!!!") is False

    def test_unparseable_key_is_false_not_error(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert verify_ssh_signature("not a key", challenge, _sign_raw(challenge)) is False


class TestFingerprint:
    def test_fingerprint_is_stable(self) -> None:
        assert ssh_fingerprint(_TEST_ED25519_PK) == ssh_fingerprint(_TEST_ED25519_PK)

    def test_fingerprint_differs_per_key(self) -> None:
        other_pk = (
            Ed25519PrivateKey.generate()
            .public_key()
            .public_bytes(serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH)
            .decode("ascii")
        )
        assert ssh_fingerprint(_TEST_ED25519_PK) != ssh_fingerprint(other_pk)

    def test_comment_and_type_changes_keep_identity(self) -> None:
        # The fingerprint is over the raw key bytes, so re-adding a comment or
        # switching key format does not mint a new identity.
        with_comment = _TEST_ED25519_PK + " someone@nowhere"
        assert ssh_fingerprint(with_comment) == ssh_fingerprint(_TEST_ED25519_PK)


class TestProvenance:
    def test_extension_carries_chaining_fields(self, settings: RelaySettings) -> None:
        from openburrow.relay.models import RoomRole
        from openburrow.relay.security import issue_token

        _, claims = issue_token(
            settings, room="r", member="m", subject="s", role=RoomRole.MAINTAINER
        )
        prov = provenance_extension(claims)["provenance"]
        assert prov["subject"] == "s"
        assert prov["jti"] == claims.jti
        assert prov["issuer"] == "openburrow-relay"


class TestSignatureAcrossKeyTypes:
    """Every key type the relay accepts, not only the one that is easy to fake.

    An Ed25519-only suite is what let the RSA and ECDSA path ship broken: the
    fallback built ``padding.PSS(mgf=..., algorithm=...)``, which raises
    ``AttributeError`` because ``PSS`` takes ``mgf`` and ``salt_length`` and
    ``PSS.SALT_LENGTH_DIGEST`` does not exist. Both were invisible while the
    branch never executed, and both read as "bad signature" at the call site.
    """

    def test_rsa_signature_verifies(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert verify_ssh_signature(_TEST_RSA_PK, challenge, _sign_raw_rsa(challenge)) is True

    def test_ecdsa_signature_verifies(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert verify_ssh_signature(_TEST_EC_PK, challenge, _sign_raw_ec(challenge)) is True

    def test_rsa_signature_from_another_key_rejected(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        other = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        signature = base64.b64encode(
            other.sign(challenge.encode(), padding.PKCS1v15(), hashes.SHA256())
        ).decode("ascii")
        assert verify_ssh_signature(_TEST_RSA_PK, challenge, signature) is False

    def test_ecdsa_signature_from_another_key_rejected(self) -> None:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        other = ec.generate_private_key(ec.SECP256R1())
        signature = base64.b64encode(
            other.sign(challenge.encode(), ec.ECDSA(hashes.SHA256()))
        ).decode("ascii")
        assert verify_ssh_signature(_TEST_EC_PK, challenge, signature) is False

    def test_ed25519_signature_is_not_accepted_as_rsa(self) -> None:
        # Algorithm confusion, in the one function where it would matter most:
        # bytes valid under one scheme must not verify under another.
        challenge, _ = new_ssh_challenge(secret=SECRET)
        assert verify_ssh_signature(_TEST_RSA_PK, challenge, _sign_raw(challenge)) is False


class TestFingerprintKeyTypes:
    def test_rsa_and_ec_keys_have_a_fingerprint(self) -> None:
        # ``public_bytes_raw()`` exists only on Ed25519 and Ed448, so an RSA key
        # used to raise into a bare except and fingerprint as "" — a member who
        # silently has no identity rather than an error.
        assert ssh_fingerprint(_TEST_RSA_PK).startswith("ssh:SHA256:")
        assert ssh_fingerprint(_TEST_EC_PK).startswith("ssh:SHA256:")

    def test_fingerprints_differ_across_key_types(self) -> None:
        prints = {
            ssh_fingerprint(_TEST_ED25519_PK),
            ssh_fingerprint(_TEST_RSA_PK),
            ssh_fingerprint(_TEST_EC_PK),
        }
        assert len(prints) == 3

    def test_line_that_is_not_a_public_key_has_no_fingerprint(self) -> None:
        # The type token has to agree with the blob it labels, or a line that
        # merely looks like a key would mint a real identity.
        blob = _TEST_ED25519_PK.split()[1]
        assert ssh_fingerprint(f"ssh-rsa {blob}") == ""
        assert ssh_fingerprint("ssh-ed25519") == ""
        assert ssh_fingerprint("ssh-ed25519 not-base64!!!") == ""


@pytest.mark.skipif(SSH_KEYGEN is None, reason="ssh-keygen is not installed")
class TestFingerprintMatchesSshKeygen:
    """The value an operator can check against the tool they already trust.

    The ``ssh:SHA256:`` prefix is a promise of interoperability. Asserting only
    that a fingerprint is stable and unique cannot detect breaking that promise,
    which is exactly what hashing the raw key bytes did: for Ed25519 it returned
    a digest no other SSH implementation agrees with.
    """

    @pytest.fixture(params=["ed25519", "rsa", "ecdsa"])
    def public_and_path(
        self, request: pytest.FixtureRequest, tmp_path: pathlib.Path
    ) -> tuple[str, pathlib.Path]:
        return _keygen_pair(tmp_path, request.param)

    def test_matches_ssh_keygen(self, public_and_path: tuple[str, pathlib.Path]) -> None:
        public, public_path = public_and_path
        listed = _ssh_keygen("-l", "-f", str(public_path)).stdout
        # "256 SHA256:<b64> comment (TYPE)"
        assert ssh_fingerprint(public) == f"ssh:{listed.split()[1]}"


@pytest.mark.skipif(SSH_KEYGEN is None, reason="ssh-keygen is not installed")
class TestSshsigInterop:
    """The documented client flow, run against the tool the docstring names.

    The old docstring claimed ``ssh-keygen -Y sign`` compatibility while the
    code base64-decoded its argument with ``validate=True`` — which the
    ``-----BEGIN SSH SIGNATURE-----`` armor fails immediately. Nothing tested
    the claim, so nothing contradicted it.
    """

    @pytest.fixture(params=["ed25519", "rsa", "ecdsa"])
    def signed(
        self, request: pytest.FixtureRequest, tmp_path: pathlib.Path
    ) -> tuple[str, str, str]:
        challenge, _ = new_ssh_challenge(secret=SECRET)
        return _sshsig(tmp_path, request.param, challenge, namespace=SSH_SIGNATURE_NAMESPACE)

    def test_ssh_keygen_signature_verifies(self, signed: tuple[str, str, str]) -> None:
        public, challenge, signature = signed
        assert verify_ssh_signature(public, challenge, signature) is True

    def test_tampered_challenge_rejected(self, signed: tuple[str, str, str]) -> None:
        public, challenge, signature = signed
        assert verify_ssh_signature(public, challenge + "x", signature) is False

    def test_signature_from_another_key_rejected(
        self, signed: tuple[str, str, str], tmp_path: pathlib.Path
    ) -> None:
        # The envelope carries its own copy of the key. If it is not checked
        # against the presented one, a member can sign with their own key and
        # present someone else's public key next to it.
        _, challenge, signature = signed
        other_dir = tmp_path / "other"
        other_dir.mkdir()
        other_public, _ = _keygen_pair(other_dir, "ed25519")
        assert verify_ssh_signature(other_public, challenge, signature) is False

    def test_foreign_namespace_rejected(self, tmp_path: pathlib.Path) -> None:
        # A signature harvested from another service — git uses SSHSIG too —
        # must not be replayable here.
        challenge, _ = new_ssh_challenge(secret=SECRET)
        public, _, signature = _sshsig(tmp_path, "ed25519", challenge, namespace="git")
        assert verify_ssh_signature(public, challenge, signature) is False

    def test_truncated_envelope_rejected(self, signed: tuple[str, str, str]) -> None:
        public, challenge, signature = signed
        body = [ln for ln in signature.strip().splitlines() if not ln.startswith("-----")]
        assert verify_ssh_signature(public, challenge, "".join(body[:-1])) is False

    def test_corrupted_envelope_rejected(self, signed: tuple[str, str, str]) -> None:
        public, challenge, signature = signed
        body = [ln for ln in signature.strip().splitlines() if not ln.startswith("-----")]
        last = body[-1]
        body[-1] = last[:-1] + ("A" if last[-1] != "A" else "B")
        assert verify_ssh_signature(public, challenge, "".join(body)) is False

    def test_missing_armor_trailer_is_accepted(self, signed: tuple[str, str, str]) -> None:
        # The trailer is cosmetic: everything that gets verified lives in the
        # base64 body, so being strict about it would reject a client that
        # stripped it without making anything safer. Dropping a body line, in
        # the test above, is the case that has to fail.
        public, challenge, signature = signed
        assert verify_ssh_signature(public, challenge, signature.strip()[:-1]) is True
