"""A2A transport: JSON-RPC 2.0 envelopes and SSE framing."""

from openburrow.a2a.transport.jsonrpc import (
    A2A_METHODS,
    CONTENT_TYPE_NOT_SUPPORTED,
    INTERNAL_ERROR,
    INVALID_PARAMS,
    INVALID_REQUEST,
    METHOD_NOT_FOUND,
    PARSE_ERROR,
    PUSH_NOT_SUPPORTED,
    TASK_NOT_CANCELABLE,
    TASK_NOT_FOUND,
    UNSUPPORTED_OPERATION,
    JsonRpcError,
    JsonRpcRequest,
    coerce_task_payload,
    iterate_sse,
    make_error,
    make_request,
    make_response,
    parse_sse_frames,
    sse_frame,
)

__all__ = [
    "A2A_METHODS",
    "CONTENT_TYPE_NOT_SUPPORTED",
    "INTERNAL_ERROR",
    "INVALID_PARAMS",
    "INVALID_REQUEST",
    "METHOD_NOT_FOUND",
    "PARSE_ERROR",
    "PUSH_NOT_SUPPORTED",
    "TASK_NOT_CANCELABLE",
    "TASK_NOT_FOUND",
    "UNSUPPORTED_OPERATION",
    "JsonRpcError",
    "JsonRpcRequest",
    "coerce_task_payload",
    "iterate_sse",
    "make_error",
    "make_request",
    "make_response",
    "parse_sse_frames",
    "sse_frame",
]
